server:
  port: 8081

spring:
  application:
    name: calc-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.portfolio.calc: DEBUG
